3

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -52,23 +52,20 @@ before_install:
     - time sh ./misc/travis-install-bashate-deb.sh || time sh ./misc/travis-install-bashate-pip.sh
 
     # "brew update" (or auto-update when installing) takes a long time,
-    # but checkbashisms and shellcheck can be installed without this
+    # but checkbashisms and shellcheck can (usually) be installed without this
     # So try installing with "HOMEBREW_NO_AUTO_UPDATE=1", which considerably reduces job time on macOS
     # If it fails retry each individually with auto-update enabled
     - |
       set -x
 
       if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
-          if HOMEBREW_NO_AUTO_UPDATE=1 brew install checkbashisms shellcheck yq; then
-              # everything worked, nothing more to do:
-              :
-          fi
-      else
-          # Note: ./tests/shell-checks will skip the tests on OSX (homebrew can be flaky) if they aren't available (but not on Linux).
-          # Still want to try to get both Linux/OSX, since they may have different versions.
-          for tool in checkbashisms shellcheck yq; do
-              if [[ ! -x "$(command -v \"$tool\")" ]]; then
-                  time brew install "$tool" || true
+          for pkg in checkbashisms shellcheck yq; do
+              if HOMEBREW_NO_AUTO_UPDATE=1 brew install "$pkg"; then
+                  # everything worked, nothing more to do:
+                  :
+              else
+                  # Allow failure, since homebrew can be flaky (the tests will still run on linux).
+                  time brew install "$pkg" || true
               fi
           done
       fi
